# Generated by Django 2.2.3 on 2019-08-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
